// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6_Ul5yz7Qr_NzeDQU2AmLkMIZz41QB1M',
    appId: '1:975763356650:web:a3b0cb536584fd48945093',
    messagingSenderId: '975763356650',
    projectId: 'strada-c3a18',
    authDomain: 'strada-c3a18.firebaseapp.com',
    storageBucket: 'strada-c3a18.firebasestorage.app',
    measurementId: 'G-ZJSQ45M83W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABKTq4UlTLv4zcSZw4PDhzVKR9gPmErvA',
    appId: '1:975763356650:android:a8c0c58c2d6f7c9a945093',
    messagingSenderId: '975763356650',
    projectId: 'strada-c3a18',
    storageBucket: 'strada-c3a18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFLd5iBU1bgqidMDvdi14EX59XP9OFzus',
    appId: '1:975763356650:ios:0ed9ebfc4d006f7a945093',
    messagingSenderId: '975763356650',
    projectId: 'strada-c3a18',
    storageBucket: 'strada-c3a18.firebasestorage.app',
    iosBundleId: 'com.stradapk.stradapk',
  );
}
